version: "3"

services:

  # NGINX
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_docker_symfony_setup
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
      - ./Docker/vhosts/vhosts.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - www-php81
      - db
    networks:
      - dev

  # DB
  db:
    image: mysql
    container_name: db_docker_symfony_setup
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

  # PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony_setup
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

  # PHP
  www-php81:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: www_php81_docker_symfony_setup
    restart: always
    ports:
      - "8000:80"
    stdin_open: true
    tty: true
    volumes:
      - ./:/var/www/
    networks:
      - dev

volumes:
  db-data:

networks:
  dev: